<fieldset>
    <legend>Dados da empresa</legend>
    <div class="form-grid">
        <div class="field"><label for="cnpj">CNPJ</label><input id="cnpj" name="cnpj" value="{{ old('cnpj', $company->cnpj ?? '') }}" maxlength="18" inputmode="numeric" placeholder="00.000.000/0000-00" required>@error('cnpj')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="phone">Telefone</label><input id="phone" name="phone" type="tel" value="{{ old('phone', $company->phone ?? '') }}" maxlength="20" placeholder="(00) 00000-0000" required>@error('phone')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field field-wide"><label for="corporate_name">Nome empresarial</label><input id="corporate_name" name="corporate_name" value="{{ old('corporate_name', $company->corporate_name ?? '') }}" maxlength="255" required>@error('corporate_name')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field field-wide"><label for="trade_name">Nome fantasia</label><input id="trade_name" name="trade_name" value="{{ old('trade_name', $company->trade_name ?? '') }}" maxlength="255" required>@error('trade_name')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field field-wide"><label for="address_street">Rua</label><input id="address_street" name="address_street" value="{{ old('address_street', $company->address_street ?? '') }}" maxlength="255" placeholder="Nome da rua ou avenida" required autocomplete="address-line1">@error('address_street')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="address_number">Número</label><input id="address_number" name="address_number" value="{{ old('address_number', $company->address_number ?? '') }}" maxlength="30" required>@error('address_number')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="address_neighborhood">Bairro</label><input id="address_neighborhood" name="address_neighborhood" value="{{ old('address_neighborhood', $company->address_neighborhood ?? '') }}" maxlength="255" required>@error('address_neighborhood')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="address_zip">CEP</label><input id="address_zip" name="address_zip" value="{{ old('address_zip', $company->address_zip ?? '') }}" maxlength="9" inputmode="numeric" placeholder="00000-000" required autocomplete="postal-code">@error('address_zip')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="address_complement">Complemento</label><input id="address_complement" name="address_complement" value="{{ old('address_complement', $company->address_complement ?? '') }}" maxlength="255" placeholder="Sala, bloco ou referência (opcional)">@error('address_complement')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="latitude">Latitude para o ponto</label><input id="latitude" name="latitude" type="number" step="0.0000001" value="{{ old('latitude', $company->latitude ?? '') }}" placeholder="-2.5300000">@error('latitude')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="longitude">Longitude para o ponto</label><input id="longitude" name="longitude" type="number" step="0.0000001" value="{{ old('longitude', $company->longitude ?? '') }}" placeholder="-44.3000000">@error('longitude')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="attendance_radius_meters">Raio permitido (metros)</label><input id="attendance_radius_meters" name="attendance_radius_meters" type="number" min="20" max="5000" value="{{ old('attendance_radius_meters', $company->attendance_radius_meters ?? 100) }}" required>@error('attendance_radius_meters')<p class="error">{{ $message }}</p>@enderror</div>
    </div>
</fieldset>

<fieldset>
    <legend>Dados do responsável</legend>
    <div class="form-grid">
        <div class="field field-wide"><label for="responsible_name">Nome completo</label><input id="responsible_name" name="responsible_name" value="{{ old('responsible_name', $company->responsible_name ?? '') }}" maxlength="255" required>@error('responsible_name')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="responsible_cpf">CPF</label><input id="responsible_cpf" name="responsible_cpf" value="{{ old('responsible_cpf', $company->responsible_cpf ?? '') }}" maxlength="14" inputmode="numeric" placeholder="000.000.000-00" required>@error('responsible_cpf')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="responsible_rg">RG</label><input id="responsible_rg" name="responsible_rg" value="{{ old('responsible_rg', $company->responsible_rg ?? '') }}" maxlength="30" placeholder="Número do RG" required>@error('responsible_rg')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="responsible_phone">Telefone</label><input id="responsible_phone" name="responsible_phone" type="tel" value="{{ old('responsible_phone', $company->responsible_phone ?? '') }}" maxlength="20" placeholder="(00) 00000-0000" required>@error('responsible_phone')<p class="error">{{ $message }}</p>@enderror</div>
        <div class="field field-wide"><label for="responsible_address">Endereço do responsável</label><input id="responsible_address" name="responsible_address" value="{{ old('responsible_address', $company->responsible_address ?? '') }}" maxlength="255" placeholder="Rua, número, bairro, cidade - UF" required>@error('responsible_address')<p class="error">{{ $message }}</p>@enderror</div>
    </div>
</fieldset>
