<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Editar aluno - {{ config('app.name', 'Stagium') }}</title>@fonts
    <style>
        :root{--bg:#f6f8fb;--surface:#fff;--text:#122033;--muted:#637083;--border:#d8e2ee;--accent:#155ea8;--danger:#b42318;font-family:"Instrument Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}.page{min-height:100vh;padding:40px 24px}.wrap{width:min(100%,760px);margin:auto}.header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;border-bottom:1px solid var(--border);padding-bottom:24px}.brand{margin:0 0 4px;color:var(--accent);font-size:14px;font-weight:700}h1{margin:0;font-size:34px}.tabs{display:flex;gap:4px;border:1px solid var(--border);border-radius:8px;background:#fff;padding:4px}.tab{border-radius:6px;color:var(--muted);padding:8px 16px;font-size:14px;font-weight:700;text-decoration:none}.tab.active{background:var(--accent);color:#fff}.panel{margin-top:32px;border:1px solid var(--border);border-radius:8px;background:var(--surface);padding:24px;box-shadow:0 8px 24px rgba(18,32,51,.06)}h2{margin:0 0 4px;font-size:18px}.hint{color:var(--muted);font-size:14px}.main-form{margin-top:24px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px 16px}.field-wide{grid-column:1/-1}label{display:block;font-size:14px;font-weight:650}input,select{width:100%;margin-top:8px;border:1px solid #c8d5e4;border-radius:6px;background:#fff;color:var(--text);padding:10px 12px;font:inherit;font-size:14px}.error{margin:6px 0 0;color:var(--danger);font-size:13px}.buttons{display:flex;align-items:center;gap:12px;margin-top:22px}.primary{border:0;border-radius:6px;background:var(--accent);color:#fff;padding:11px 16px;font:inherit;font-weight:700;cursor:pointer}.cancel{color:var(--muted);padding:11px 16px;text-decoration:none;font-size:14px;font-weight:700}@media(max-width:640px){.page{padding:24px 14px}.header{align-items:flex-start;flex-direction:column}.tabs{width:100%}.tab{flex:1;text-align:center}.form-grid{grid-template-columns:1fr}.field-wide{grid-column:auto}}
    </style>
</head>
<body><div class="page"><main class="wrap"><header class="header"><div><p class="brand">Stagium</p><h1>Editar aluno</h1></div><nav class="tabs"><a href="{{ route('dashboard') }}" class="tab">Dashboard</a><a href="{{ route('courses.index') }}" class="tab">Início</a><a href="{{ route('students.index') }}" class="tab active">Alunos</a></nav></header>
<section class="panel"><h2>{{ $student->name }}</h2><p class="hint">Atualize os dados cadastrais do aluno.</p><form class="main-form" action="{{ route('students.update', $student) }}" method="POST">@csrf @method('PUT') @include('students._form')<div class="buttons"><button class="primary" type="submit">Salvar alterações</button><a class="cancel" href="{{ route('students.index') }}">Cancelar</a></div></form></section>
</main></div></body></html>
